server:
  port: 8004

spring:
  application:
    name: huiyi-activiti
  profiles: 
    active: dev
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activiti:
    check-process-definitions: false

feign:
  hystrix:
    enabled: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.huiyi
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

mapper:
  not-empty: true
  identity: MYSQL

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql       