# 日志配置
logging:
  level:
    com.huiyi: debug
    org.springframework: warn

spring:
  redis:
    database: 1
    host: 172.16.112.38
    port: 8379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://172.16.112.38:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址     
