server: 
  port: 9527
 
spring: 
  application:
    name: huiyi-gateway
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: huiyi-auth
          uri: lb://huiyi-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: huiyi-gen
          uri: lb://huiyi-gen
          predicates:
            - Path=/gen/**
          filters:
            - StripPrefix=1
        # dfs
        - id: huiyi-dfs
          uri: lb://huiyi-dfs
          predicates:
            - Path=/dfs/**
          filters:
            - StripPrefix=1
        # act
        - id: huiyi-activiti
          uri: lb://huiyi-activiti
          predicates:
            - Path=/act/**
          filters:
            - StripPrefix=1
        #system 模块
        - id: huiyi-system
          uri: lb://huiyi-system
          predicates:
            - Path=/system/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        #biz 模块
        - id: huiyi-biz
          uri: lb://huiyi-biz
          predicates:
            - Path=/biz/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'

hystrix:
    command:
      default:  #default全局有效，service id指定应用有效
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'