# 日志配置
logging:
  level:
    com.huiyi: debug
    org.springframework: warn

dfs:
  path: /root/upload
  domain: http://172.16.112.38:8006/

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://172.16.112.38:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
