# 日志配置
logging:
  level:
    com.huiyi: debug
    org.springframework: warn

dfs:
  path: /Users/gaojiaqi/Documents/项目/opensource/huiyi-chain/huiyi-service/huiyi-dfs/src/main/resources/upload
  domain: http://127.0.0.1:8006/

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
